### ISSUE TITLE
I need a permission.

### ISSUE THREAD

**Issue by aferust** [dbarac/sift-cpp#3]
Hello,

Thank you for the awesome work. I have translated this SIFT implementation to dlang to include it in DCV (an open-source CV library). I am one of the maintainers. Of course, all the credit will be given to @dbarac by explicitly mentioning in the source file and a reference to this repo.

Thanks in advance
Ferhat

https://github.com/libmir/dcv

**Comment by dbarac** [comment]
Thank you, it is ok for me, you can include it.

**Comment by aferust** [comment]
Thank you, @dbarac, here it is:

https://github.com/libmir/dcv/blob/master/source/dcv/features/sift.d
https://github.com/libmir/dcv/tree/master/examples/sift

Please feel free to ask anything related to the way I include it in the codebase of DCV
